### ISSUE TITLE
What is `ap`?

### ISSUE THREAD

**Issue by nating** [McGizzle/CS4012-Functional-Programming#1]
https://github.com/McGizzle/CS4012-Functional-Programming/blob/4ac335f47b73279fb1010f73639fed55727d236c/MaybeT.hs#L19

Here you have defined the applicative `<*>` function as being `ap`. What is `ap`? Or have you forgotten to define it? There is a similar reference to it [here](https://github.com/McGizzle/CS4012-Functional-Programming/blob/4ac335f47b73279fb1010f73639fed55727d236c/EitherT.hs#L20) in EitherT.hs

Thanks!

**Comment by mcgizzle** [comment]
`ap` does the work for defining the applicative instance for us, it comes from `Control.Monad`.

its type is `Monad m => m (a -> b) -> m a -> m b` which looks exactly like what we need.

Heres the implementation `ap m1 m2          = do { x1 <- m1; x2 <- m2; return (x1 x2) }`
Whats happening here is it is doing both actions monadically, then applying their results in the applicative style.

[Here you can find out more about it ](http://hackage.haskell.org/package/base-4.10.1.0/docs/Control-Monad.html#v:ap)

**Comment by nating** [comment]
That explains it!

Thanks very much again, @McGizzle!
